title: Siyi Chen's Homepage
page-top-title: Siyi(Charles) Chen
top-section-bg-text: Computer Science
home-subtitle: Siyi Chen&ensp;|&ensp;陈思屹
copyright-text: '&copy; Siyi Chen 2023-2024. All Rights Reserved.'
